using Bennewitz.Ninja.CodeQuality.Rules;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;

namespace CodeQuality.Tests.Rules;

/// <summary>
/// BNCQ1004 fires on a segment that repeats a referenced root, and on nothing else.
/// </summary>
public sealed class NamespaceShadowTests
{
    /// <summary>
    /// The .NET reference pack declares <c>System</c> in its <c>System.*</c> assemblies, so the root
    /// is found without reading forwarded types. Its <c>mscorlib</c> and <c>netstandard</c> are
    /// facades that declare nothing, and they are not what supplies it.
    /// </summary>
    [Fact]
    public Task A_segment_repeating_System_from_the_reference_assemblies_fires() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace Acme.Widgets.{|BNCQ1004:System|}
            {
                public class Widget { }
            }
            """);

    [Fact]
    public Task A_file_scoped_declaration_fires_too() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace Acme.{|BNCQ1004:System|};

            public class Widget { }
            """);

    /// <summary>
    /// A nested declaration has no first segment of its own: the enclosing one supplied it.
    /// </summary>
    [Fact]
    public Task Every_segment_of_a_nested_declaration_is_checked() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace Acme
            {
                namespace {|BNCQ1004:System|}.Widgets
                {
                    public class Widget { }
                }
            }
            """);

    [Fact]
    public Task Two_shadowing_segments_are_two_findings() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace Acme.{|BNCQ1004:System|}.{|BNCQ1004:Microsoft|}
            {
                public class Widget { }
            }
            """);

    /// <summary>
    /// The first segment is the tree the namespace already lives in: <c>System.Acme</c> resolves
    /// through the merged <c>System</c>, and so does everything else.
    /// </summary>
    [Fact]
    public Task The_first_segment_never_fires() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace System.Acme
            {
                public class Widget { }
            }
            """);

    /// <summary>
    /// <c>Collections</c> is a namespace under <c>System</c>, not a root: <c>Acme.Collections</c>
    /// shadows nothing, because no qualified name starts with <c>Collections</c>.
    /// </summary>
    [Fact]
    public Task A_segment_repeating_a_nested_referenced_namespace_stays_silent() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace Acme.Collections.Generic
            {
                public class Widget { }
            }
            """);

    [Fact]
    public Task A_clean_namespace_stays_silent() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            namespace Acme.Widgets.Controls
            {
                public class Widget { }
            }
            """);

    [Fact]
    public Task Generated_code_is_not_analyzed() =>
        RuleTest<NamespaceShadowAnalyzer>.Run("""
            // <auto-generated/>
            namespace Acme.System
            {
                public class Widget { }
            }
            """);

    /// <summary>
    /// A referenced project's root counts, and the message names that assembly.
    /// </summary>
    [Fact]
    public async Task A_root_declared_by_a_referenced_project_fires_and_names_it()
    {
        RuleTest<NamespaceShadowAnalyzer> test = new("""
            namespace Acme.{|#0:Vendor|}
            {
                public class Widget { }
            }
            """);
        test.TestState.AdditionalProjects["Vendor"].Sources.Add("""
            namespace Vendor
            {
                public class Shown { }
            }
            """);
        test.TestState.AdditionalProjectReferences.Add("Vendor");
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult(NamespaceShadowAnalyzer.Id, DiagnosticSeverity.Warning)
                .WithLocation(0)
                .WithArguments("Vendor", "the referenced assembly 'Vendor'"));

        await test.Run();
    }

    /// <summary>
    /// A root many assemblies declare is attributed to one a reader recognises, with the count.
    /// Measured: attributing it to the first in reference order named Microsoft.Win32.Primitives
    /// for System, because the reference pack is listed alphabetically.
    /// </summary>
    [Fact]
    public async Task A_root_many_assemblies_declare_names_one_after_it_and_counts_them()
    {
        Plain.Run run = await Plain.Analyze(new NamespaceShadowAnalyzer(), """
            namespace Acme.System
            {
                public class Widget { }
            }
            """, await Plain.Net80());

        Assert.Empty(run.Errors);
        Diagnostic finding = Assert.Single(run.Diagnostics);
        Assert.Matches("declared by [0-9]+ referenced assemblies, 'System\\.[A-Za-z.]+' among them", finding.GetMessage());
    }

    /// <summary>
    /// A reference behind an extern alias adds nothing to the global namespace: its root is reached
    /// only as <c>V::Vendor</c>, so a segment named <c>Vendor</c> shadows nothing. Found by review:
    /// the first version reported it.
    /// </summary>
    [Fact]
    public async Task A_root_reachable_only_through_an_extern_alias_stays_silent()
    {
        Images.Image vendor = await Images.Compile("Vendor", """
            namespace Vendor
            {
                public class Shown { }
            }
            """);

        RuleTest<NamespaceShadowAnalyzer> test = new("""
            extern alias V;

            namespace Acme.Vendor
            {
                public class Widget
                {
                    public V::Vendor.Shown Shown { get; set; }
                }
            }
            """);
        test.TestState.AdditionalReferences.Add(vendor.Reference.WithAliases(["V"]));

        await test.Run();
    }

    /// <summary>
    /// An alias list that includes <c>global</c> puts the root in the global namespace as well, so
    /// the shadow is real again.
    /// </summary>
    [Fact]
    public async Task A_root_aliased_and_global_fires()
    {
        Images.Image vendor = await Images.Compile("Vendor", """
            namespace Vendor
            {
                public class Shown { }
            }
            """);

        RuleTest<NamespaceShadowAnalyzer> test = new("""
            namespace Acme.{|BNCQ1004:Vendor|}
            {
                public class Widget { }
            }
            """);
        test.TestState.AdditionalReferences.Add(vendor.Reference.WithAliases(["global", "V"]));

        await test.Run();
    }

    /// <summary>
    /// A namespace holding only internal types cannot be named from here, so nothing is shadowed.
    /// </summary>
    [Fact]
    public async Task A_root_with_only_internal_types_stays_silent()
    {
        RuleTest<NamespaceShadowAnalyzer> test = new("""
            namespace Acme.Vendor
            {
                public class Widget { }
            }
            """);
        test.TestState.AdditionalProjects["Vendor"].Sources.Add("""
            namespace Vendor
            {
                internal class Hidden { }
            }
            """);
        test.TestState.AdditionalProjectReferences.Add("Vendor");

        await test.Run();
    }

    /// <summary>
    /// With the internals made visible, the same namespace can be named, and is shadowed.
    /// </summary>
    [Fact]
    public async Task A_root_with_internals_visible_to_this_assembly_fires()
    {
        RuleTest<NamespaceShadowAnalyzer> test = new("""
            namespace Acme.{|BNCQ1004:Vendor|}
            {
                public class Widget { }
            }
            """);
        test.TestState.AdditionalProjects["Vendor"].Sources.Add("""
            [assembly: System.Runtime.CompilerServices.InternalsVisibleTo("TestProject")]

            namespace Vendor
            {
                internal class Hidden { }
            }
            """);
        test.TestState.AdditionalProjectReferences.Add("Vendor");

        await test.Run();
    }

    /// <summary>
    /// Outside its scope the rule registers nothing: with no reference declaring a namespace, a
    /// segment has nothing to shadow, and even the name <c>System</c> passes.
    /// </summary>
    [Fact]
    public async Task With_no_references_the_rule_registers_nothing()
    {
        const string Source = """
            namespace Acme.System
            {
                public class Widget { }
            }
            """;

        Plain.Run inert = await Plain.Analyze(new NamespaceShadowAnalyzer(), Source, []);
        Plain.Run control = await Plain.Analyze(new NamespaceShadowAnalyzer(), Source, await Plain.Net80());

        Assert.Equal(0, inert.Registrations);
        Assert.Empty(inert.Diagnostics);
        Assert.True(control.Registrations > 0, "In scope, the rule registered nothing, so a zero proves nothing.");
        Assert.Single(control.Diagnostics);
    }
}
